import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from '../../components/shared/NavBar';
import Footer from '../../components/shared/Footer';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer} from 'react-toastify';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="">
        <NavBar/>
            <section className="flex min-h-screen w-full px-6 sm:px-8 md:px-10 lg:px-20 pb-6">
                {children}
            </section>
            <ToastContainer />
        <Footer/>
    </main>
  );
}
